// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskTracker.Data.Context;

#nullable disable

namespace TaskTracker.Migrations
{
    [DbContext(typeof(TaskTrackerDbContext))]
    [Migration("20250906161932_SampleData")]
    partial class SampleData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TaskTracker.Entities.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("activities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1a1f1ee-6c54-4b01-90e6-d701748f0851"),
                            CreatedAt = new DateTime(2025, 9, 6, 16, 19, 30, 910, DateTimeKind.Utc).AddTicks(7109),
                            Description = "This is a sample activity description.",
                            DueDate = new DateTime(2025, 9, 13, 16, 19, 30, 910, DateTimeKind.Utc).AddTicks(1616),
                            IsActive = true,
                            IsCompleted = false,
                            LastModifiedAt = new DateTime(2025, 9, 6, 16, 19, 30, 910, DateTimeKind.Utc).AddTicks(7565),
                            Title = "Sample Activity"
                        });
                });

            modelBuilder.Entity("TaskTracker.Entities.ErrorLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StackTrace")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("error_logs");
                });

            modelBuilder.Entity("TaskTracker.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("tags");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d290f1ee-6c54-4b01-90e6-d701748f0851"),
                            CreatedAt = new DateTime(2025, 9, 6, 16, 19, 30, 908, DateTimeKind.Utc).AddTicks(899),
                            IsActive = true,
                            LastModifiedAt = new DateTime(2025, 9, 6, 16, 19, 30, 908, DateTimeKind.Utc).AddTicks(1417),
                            Name = "Sample Tag"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
